name: Feature Request
description: Suggest an idea or improvement for Classic Fishing Companion
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it! Fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: "\U0001F4A1 What problem does this solve?"
      description: Describe the limitation or friction you're running into.
      placeholder: e.g. I have to manually track X every session and it's tedious...
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: "\u2728 Describe the Feature"
      description: A clear description of what you'd like to see added or changed.
      placeholder: I'd like...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "\U0001F3A3 How would you use it?"
      description: Walk us through a typical use case.
      placeholder: e.g. I'd open the Goals tab, pick a fish, and set a target count...

  - type: checkboxes
    id: client
    attributes:
      label: "\u2139\uFE0F WoW Client"
      description: Which client(s) should this apply to?
      options:
        - label: Classic Era
        - label: TBC Classic
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "\U0001F4DD Additional Context"
      description: Mockups, examples from other addons, or anything else that helps paint the picture.
